before_script:
  - export GOPATH=/golang
  - export PATH=$PATH:$GOPATH/bin
  - mkdir -p /golang/src/k2http2/
  - mv * /golang/src/k2http2/
  - cd /golang/src/k2http2/

stages:
  - build
  - test

build-go-1.5:
  image: golang:1.5
  stage: build
  script:
    - make get
    - make

test-go-1.5:
  image: golang:1.5
  stage: test
  only:
    - master
    - develop
  script:
    - make get
    - make test
    - make coverage
