sudo: required

language: go

go: 
  - 1.6.2

services:
  - docker

before_install: 
  - sudo apt-get -qq update

install:
  - make get
  - make get_dev
  - make

script :
  - make fmt
  - make vet
  - make test
  - make integration-tests
